@echo off
cd /d "%~dp0"
if not exist "venv" (
    echo [StreamVault] Virtual environment not found. Creating one...
    python -m venv venv
)
echo [StreamVault] Activating virtual environment...
call venv\Scripts\activate.bat
echo [StreamVault] Installing/checking dependencies...
pip install -r requirements.txt
echo [StreamVault] Launching application...
python gui.py
