@echo off
cd /d "%~dp0"
if not exist "venv" (
    echo [Koinloader] Virtual environment not found. Creating one...
    python -m venv venv
)
echo [Koinloader] Activating virtual environment...
call venv\Scripts\activate.bat
echo [Koinloader] Installing/checking dependencies...
pip install -r requirements.txt
echo [Koinloader] Launching application...
python gui.py
